### PR TITLE
chore: start using node-pre-gyp

### PR DESCRIPTION
**Pull request by nolanmar511**
This is preparation for #47.

Right now, we call NODE_MODULE() twice (in sampling-heap-profiler, and in time-profiler), and generate two separate binaries (one for sampling-heap-profiler, and one for time-profiler).

`node-pre-gyp` requires that the "module_name" in the package.json has to match the name passed to the NODE_MODULE macro. There isn't a way to specify the "module_name" twice, this change refactors, so that the NODE_MODULE macro is only called once.

### CODE REVIEW

**Comment by aalexand** [comment]
@nolanmar511 What is a "node" file?

It is also not clear why you had to switch to use objects instead of free functions, could you elaborate on that (here or just in the PR description).

**Comment by nolanmar511** [comment]
Tried to clarify the description, and switched back to using free functions.

**Comment by aalexand** [comment]
@nolanmar511 Would things be simpler overall if we'd just put all bindings to a single profiler.cc file? The interface to both of time and heap profiler is tiny and I feel that we have unnecessary complexity when we put them into separate files and then have two Init functions and a wrapper around that to call both Init's etc.

**Comment by nolanmar511** [comment]
I'm not opposed to putting everything one one file. There are three reasons I separated these out.  First, I feel like logically separating these might make it easier to ultimately transition to using the sampling-heap-profiler node module, which is something we've planned to do. Next is that we'd have to rename StartProfiling, StopProfiling, and SetSamplingInterval for the time profiler. And finally, if we add ever add profile types, the single profile.cc file could get too large.

None of these things are particularly strong reasons not to put everything in one file, though.

Another alternative is to keep the structure, but move everything in TimeProfilerInit and SamplingHeapProfilerInit directly into the Init function in profiler.cc.

**Comment by aalexand** [comment]
@nolanmar511 I think I'd put everything in one file but would skip on the renaming part. Yes, the names are slightly inconsistent, but that's minor I think.

**Pull request merged**
