### PR TITLE
fix: add empty go file to allow integration test to be run as go test

### PR DESCRIPTION
**Pull request by nolanmar511**

### CODE REVIEW

**Comment by aalexand** [comment]
@nolanmar511 Why did this error started to happen and didn't happen before? Did version of Go get updated in Kokoro VMs?

**Comment by aalexand** [comment]
I think https://github.com/googleapis/cloud-profiler-nodejs/pull/377 is a better solution, I merged it.

**Comment by nolanmar511** [comment]
#377 is better fix. 

Abandoning this change

**Comment by nolanmar511** [comment]
And, we don't print the version of go used by the kokoro machine, so I'm not sure if the go version changed. My assumption, though, is that the go version did change.

**Pull request closed without merging**
