### PR TITLE
DO NOT LAND: direct pprof support

### PR DESCRIPTION
**Pull request by ofrobots**
Experimenting with a way to get this module to generate pprof output directly.

### CODE REVIEW

**Comment by ofrobots** [comment]
So it would be good if we could split the `src/profilers` directory + native bindings into a separate module and expose the `start` and `stop` functions directly. The control, options and auth logic for profiling can continue to remain in the this module; which will become a pure-js module.

**Comment by nolanmar511** [comment]
+1 to splitting `src/profilers` directory + native bindings into a separate module and expose the `start` and `stop` functions directly.

I would really love to get to the point where we could have have a module that, like go's ["net/http/pprof" package](https://golang.org/pkg/net/http/pprof/).

**Comment by ofrobots** [comment]
Any suggestions for the name of the extracted pprof-based profling module?

- `pprof`: may be confused with the pprof tool itself?
- `pprof-profiler`: seemingly redundant name seems redundant. Hopeful the first `p` doesn't stand for `profiler` as well :)
- `node-pprof`

**Comment by aalexand** [comment]
Splitting seems reasonable. For naming, how about `pprof-nodejs`? Seems to play well with `cloud-profiler-nodejs`.

**Comment by ofrobots** [comment]
@aalexand for the repo name that would work. But for the npm module name, the `nodejs` part would be redundant. I personal vote is for `pprof` as the module name. The confusion can be managed in the README.

**Comment by aalexand** [comment]
@ofrobots SGTM. Would the repo be googleapis/pprof-nodejs or google/pprof-nodejs? The latter is closer to google/pprof.

**Comment by ofrobots** [comment]
IMO it should be `google/pprof-nodejs`. The module would add pprof profiling support for Node.js. It doesn't have anything to do with Google APIs, so it makes sense for it to be in the google github org.

**Comment by aalexand** [comment]
I agree.

**Comment by ofrobots** [comment]
Moved to https://github.com/google/pprof-nodejs/pull/8.

**Pull request closed without merging**
