### PR TITLE
chore: finish separating kokoro configs into multiple directories

### PR DESCRIPTION
**Pull request by nolanmar511**
Finishes changes started in #407.

Also adds common configs to each directory with kokoro configs.

### CODE REVIEW

**Comment by aalexand** [comment]
@nolanmar511 There is Kokoro build failure?

**Comment by nolanmar511** [comment]
The failure was real. Fixed by adding common.cfg to directories for presubmit, continuous, and release configs.

**Comment by nolanmar511** [comment]
PTAL

**Comment by nolanmar511** [comment]
I'm merging this change to reduce noise, since it should fix continuous test failures we're seeing.

**Pull request merged**
