### PR TITLE
v0.3.0

### PR DESCRIPTION
**Pull request by nolanmar511**
Release notes: https://github.com/googleapis/cloud-profiler-nodejs/releases/edit/untagged-0029200f20cca0660243

### CODE REVIEW

**Comment by ofrobots** [comment]
AFAICT, there are no breaking changes. Can you make that explicit in the release notes?

Secondly, is there a reason not to go to 1.0.0 (i.e. API stable) at this point. It seems that this module has a stable user-exposed API. Once you have 1.0.0, people can derive meaningful information just from the version for a given release. In the 0.x.y, people have to read the release notes carefully to understand whether they would expect any breakage.

**Comment by aalexand** [comment]
@ofrobots @nolanmar511 I am sorry, I merged the PR by mistake. We should probably revert since there are comments from ofrobots.

**Comment by nolanmar511** [comment]
NP -- I have a PR to revert this one.

Once that's in 

I think the next release can be 1.0.0.

The only thing that's been holding me back from 1.0.0, at least, has been a desire to get a bit more feature-complete first -- so have source map support finalize and have at least some pre-compiled binaries. But, it's probably not reasonable to wait for the agent to be more feature-complete before going to 1.0.0, especially given that I don't expect the API to change.

**Comment by ofrobots** [comment]
In semver, (especially in the npm ecosystem), 1.0.0 is not about feature completeness, it is about setting expectations with your users that you are willing to use the version to communicate the semver impact of the changes. In fact, the recommended practice is to *start* with 1.0.0 for the first version.

**Pull request merged**
