### PR TITLE
DO NOT REVIEW, fix: move @type dependencies to devDependencies

### PR DESCRIPTION
**Pull request by nolanmar511**
Fixes #435 

Currently just running e2e test to see if these type definitions are needed or not.

### CODE REVIEW

**Comment by aalexand** [comment]
@nolanmar511 Kokoro build failed?

**Comment by nolanmar511** [comment]
Yep -- kokoro build is failing because we actually do need one of the @types packages.

I should have included "DO NOT REVIEW" when I created the PR, instead of adding it shortly after. I knew the e2e test would fail if either package I removed was needed for typescript.

**Comment by aalexand** [comment]
@nolanmar511 OK, I'll ignore this PR then.

**Comment by JustinBeckwith** [comment]
@nolanmar511 can we close this out?

**Comment by nolanmar511** [comment]
Yes -- this can be closed.

**Pull request closed without merging**
